-- Tables

CREATE TABLE patients (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(16),
  date_of_birth date,
  PRIMARY KEY(id)
);

CREATE TABLE medical_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  admitted_at timestamp,
  patient_id INT,
  status VARCHAR,
  PRIMARY KEY(id)
);

CREATE TABLE invoices (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  total_amount DECIMAL,
  generated_at timestamp,
  payed_at timestamp,
  medical_history_id INT,
  PRIMARY KEY(id)
);

CREATE TABLE invoice_items (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  unit_price DECIMAL,
  quantity INT,
  total_price DECIMAL,
  invoice_id INT,
  treatment_id INT,
  PRIMARY KEY(id)
);

CREATE TABLE treatments (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR,
  name VARCHAR,
  PRIMARY KEY(id)
);

-- Foreign Keys

ALTER TABLE medical_histories ADD CONSTRAINT fk_medical_histories_patients FOREIGN KEY (patient_id) REFERENCES patients (id);
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_medical_histories FOREIGN KEY (medical_history_id) REFERENCES medical_histories (id);
ALTER TABLE invoice_items ADD CONSTRAINT fk_invoice_items_invoices FOREIGN KEY (invoice_id) REFERENCES invoices (id);
ALTER TABLE invoice_items ADD CONSTRAINT fk_invoice_items_treatments FOREIGN KEY (treatment_id) REFERENCES treatments (id);
