-- day 1
CREATE TABLE pets(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(16),
  birth_date date,
  escape_attempts INT,
  neutered bool,
  weight_kg DECIMAL,
  PRIMARY KEY(id)
);

-- day 2
ALTER TABLE pets
ADD species VARCHAR(12);

-- day 3
CREATE TABLE owners(
  id	INT GENERATED BY DEFAULT AS IDENTITY,
	full_name	VARCHAR,
	age	INT,
	PRIMARY KEY (id)
); -- Owners table

CREATE TABLE species (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name	VARCHAR,
	PRIMARY KEY (id)
); -- Species table

ALTER TABLE pets
DROP COLUMN species; -- Remove species column from pets table

ALTER TABLE pets
ADD species_id INTEGER REFERENCES species (id) -- Add species_id column to pets table

ALTER TABLE pets
ADD owner_id INTEGER REFERENCES owners (id) -- Add owner_id column to pets table

ALTER TABLE pets
ADD CONSTRAINT fk_pets_owners
FOREIGN KEY (owner_id)
REFERENCES owners (id); -- Add owner_id foreign key constraint to pets table
