-- Day 1
CREATE TABLE pets(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(16),
  birth_date date,
  escape_attempts INT,
  neutered bool,
  weight_kg DECIMAL,
  PRIMARY KEY(id)
);

-- Day 2
ALTER TABLE pets
ADD species VARCHAR(12);

-- Day 3
CREATE TABLE owners(
  id	INT GENERATED BY DEFAULT AS IDENTITY,
	full_name	VARCHAR,
	age	INT,
	PRIMARY KEY (id)
); -- Owners table

CREATE TABLE species (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name	VARCHAR,
	PRIMARY KEY (id)
); -- Species table

ALTER TABLE pets
DROP COLUMN species; -- Remove species column from pets table

ALTER TABLE pets
ADD species_id INTEGER REFERENCES species (id) -- Add species_id column to pets table

ALTER TABLE pets
ADD owner_id INTEGER REFERENCES owners (id) -- Add owner_id column to pets table

ALTER TABLE pets
ADD CONSTRAINT fk_pets_species
FOREIGN KEY (species_id) REFERENCES species (id); -- Add species_id foreign key to pets table

ALTER TABLE pets
ADD CONSTRAINT fk_pets_owners
FOREIGN KEY (owner_id)
REFERENCES owners (id); -- Add owner_id foreign key constraint to pets table

-- Day 4
CREATE TABLE vets (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR,
	age INT,
	graduation_date date,
	PRIMARY KEY (id)
); -- Create vets table

CREATE TABLE specializations (
	vet_id INT,
	species_id INT,
	PRIMARY KEY (vet_id, species_id),
	FOREIGN KEY (vet_id) REFERENCES vets (id),
	FOREIGN KEY (species_id) REFERENCES species (id)
); -- Create specializations join table

CREATE TABLE visits (
	vet_id INT,
	pet_id INT,
  visit_date date,
	PRIMARY KEY (vet_id, pet_id, visit_date),
	FOREIGN KEY (vet_id) REFERENCES vets (id),
	FOREIGN KEY (pet_id) REFERENCES pets (id)
); -- Create visits join table
